version: 2.1
orbs:
  node: circleci/node@7.1.0
  codecov: codecov/codecov@4.2.0
jobs:
  test:
    executor:
      name: node/default
      tag: '16.19'
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/whos-that-pokemon/node_modules
      - run: npm run test
      - codecov/upload
workflows:
    test:
      jobs:
        - test
