version: 2.1
orbs:
  node: circleci/node@5.0.2
  codecov: codecov/codecov@1.1.0
jobs:
  test:
    executor:
      name: node/default
      tag: '16'
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/whos-that-pokemon/node_modules
      - run: npm run test
      - codecov/upload:
          file: tests/coverage/*.json
workflows:
    test:
      jobs:
        - test
